// Tema 9/pokemon/src/components/Login.jsx
import React, { useState } from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import { GoogleAuthProvider, GithubAuthProvider, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup } from 'firebase/auth';
import { auth } from '../../firebase';

export function Login() {
  const navigate = useNavigate();

  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [estaIniciado, setEstaIniciado] = useState(true);
  const [confirmarContraseña, setConfirmarContraseña] = useState(''); 
  
  const googleAuthProvider = new GoogleAuthProvider();
  const githubAuthProvider = new GithubAuthProvider();

  const iniciarORegistrar = async () => {
    setError('');

    if (!estaIniciado && password !== confirmarContraseña) { 
        setError('Las contraseñas no coinciden');
        return;
    }

    try {
      if (estaIniciado) {
        await signInWithEmailAndPassword(auth, email, password);
        navigate("/")
      } 
      else {
        await createUserWithEmailAndPassword(auth, email, password);
        navigate("/")
      }
    } 
    catch (err) {
      setError(err.message);
    }
  };

  const iniciarConGoogle = async () => {
    try {
      await signInWithPopup(auth, googleAuthProvider);
      navigate("/")
    } catch (err) {
      setError(err.message);
    }
  };

  const iniciarConGithub = async () => {
    try {
      await signInWithPopup(auth, githubAuthProvider);
      navigate("/")
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <div className="formulario">
      <h2 className='tituloForm'>{estaIniciado ? 'Iniciar sesión' : 'Registrarse'}</h2>
      
      <button onClick={iniciarConGithub} className="btnGithub"><i className="fa-brands fa-github" id="logoGithub"></i> Inicia con Github</button>
      <button onClick={iniciarConGoogle} className="btnGoogle"><img src="https://www.google.com\favicon.ico" alt="Google" /> Inicia con Google</button>
      
      <hr className='separacion'/>
      
      <form className='{ estaIniciado } ? iniciarSesion : registrarse' onSubmit={(e) => { e.preventDefault(); iniciarORegistrar(); }}>
        <label>Correo</label>
        <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="ejemplo@gmail.com" required />
        
        <label>Contraseña</label>
        <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required />

        {!estaIniciado && ( 
          <>
            <label>Confirmar Contraseña</label>
            <input type="password" value={confirmarContraseña} onChange={(e) => setConfirmarContraseña(e.target.value)} required />
          </>
        )}

        <button type="submit">{estaIniciado ? 'Iniciar sesión' : 'Registrarse'}</button>
      </form>

      {error && <p className="error">{error}</p>}
      
      <p className="cambiarForm">
        {estaIniciado ? '¿No tienes ninguna cuenta?' : '¿Ya tienes una cuenta?'}
        <span onClick={() => setEstaIniciado(!estaIniciado)}>
          {estaIniciado ? 'Registrarse' : 'Iniciar sesión'}
        </span>
      </p>
    </div>
  );
}

// Tema 7 VUE/NotasJorge/src/components/Login.vue
<script setup>
    import { ref, onMounted, watch  } from 'vue'

    import { GoogleAuthProvider, createUserWithEmailAndPassword, signInWithEmailAndPassword } from 'firebase/auth'
    import {
        signInWithPopup
    } from 'firebase/auth'

    import { useCurrentUser, useFirebaseAuth } from 'vuefire'

    import { useRouter } from 'vue-router';

    const router = useRouter();
    
    
    const auth = useFirebaseAuth();
    const googleAuthProvider = new GoogleAuthProvider()
    const user = useCurrentUser()

    const error = ref("");
    const correo = ref('')
    const contraseña = ref('')
    const estaIniciado = ref(true)

    async function iniciarSesion(){
        await signInWithPopup(auth, googleAuthProvider).then(() => {
            router.push("/recordatorios");
            console.log("Validación correcta");
        })
        .catch((reason) => {
            console.error("Failed sign", reason)
        });   
    }

    function redirigir(){
        router.push("/recordatorios");
    }

    async function loginContraseña(){
        error.value = "";
        try{
            if(estaIniciado.value){
                await signInWithEmailAndPassword(auth, correo.value, contraseña.value)
            }
            else{
                await createUserWithEmailAndPassword(auth, correo.value, contraseña.value);
            }
        }
        catch(err){
            error.value = err.value;
        }
    }
    

    onMounted(() => {
        if(user){
            redirigir();
        }
    })

    watch(user, (newUser) => {
    if (newUser) {
        redirigir();
    }
});

</script>

<template>

    <div v-if="!user">
        <button @click="iniciarSesion">Iniciar Sesion con Github <img src="https://www.github.com\favicon.ico" alt="Google"></button>
        <button @click="iniciarSesion">Iniciar Sesion con Google <img src="https://www.google.com\favicon.ico" alt="Google"></button>
        
        <h2>{{ estaIniciado  ? 'Iniciar sesión' : 'Registrarse' }}</h2>
        <form class="{{ estaIniciado }} ? iniciarSesion : registrarse" @submit.prevent="loginContraseña">

            <label for="correo">Corrreo</label>
            <input type="text" name="correo" placeholder="nombre@dominio.com" id="correo" v-model="correo" required >

            <label for="contraseña">Contraseña</label>
            <input type="password" name="contraseña" id="contraseña" v-model="contraseña" placeholder="Introduce tu contraseña" required>

            <a href=""></a>

            <button type="submit">{{ estaIniciado  ? 'Iniciar sesión' : 'Registrarse' }}</button>
        </form>

        <p class="cambiarForm">
          {{ estaIniciado ? '¿No tienes ninguna cuenta?' : '¿Ya tienes una cuenta?' }}
          <span @click="estaIniciado = !estaIniciado">
            {{ estaIniciado ? 'Registrarse' : 'Iniciar sesión' }}
          </span>
        </p>

    </div>

    

</template>

<style scoped>

    label, h2{
        color: white;
    }

  
</style>
